workflows:
  unity-android-workflow:
      name: Unity Android Workflow
      instance_type: mac_mini_m1
      max_build_duration: 120
      environment:
        groups:
          # Add the group environment variables in Codemagic UI (either in Application/Team variables) - https://docs.codemagic.io/variables/environment-variable-groups/
          - unity # <-- (Includes UNITY_HOME, UNITY_SERIAL, UNITY_USERNAME and UNITY_PASSWORD)
          - keystore_credentials # <-- (Includes FCI_KEYSTORE, FCI_KEYSTORE_PASSWORD, FCI_KEY_ALIAS_PASSWORD, FCI_KEY_ALIAS_USERNAME)
          - google_play # <-- (Includes GCLOUD_SERVICE_ACCOUNT_CREDENTIALS <-- Put your google-services.json)
        vars:
          UNITY_BIN: $UNITY_HOME/Contents/MacOS/Unity
          UNITY_BIN_VERSION: /Applications/Unity/Hub/Editor/2019.4.34f1/Unity.app/Contents/MacOS/Unity
          BUILD_SCRIPT: BuildAndroid
          PACKAGE_NAME: "io.codemagic.unity" # <-- Put your package name here e.g. com.domain.myapp
        xcode: latest
      triggering:
        events:
          - push
          - tag
          - pull_request
        branch_patterns:
          - pattern: develop
            include: true
            source: true
      scripts:
        - name: Install Hub
          script: |
            curl -o ./unityhub.dmg https://public-cdn.cloud.unity3d.com/hub/prod/UnityHubSetup.dmg
            hdiutil attach ./unityhub.dmg
            cd "/Volumes/Unity Hub 3.1.1/"
            sudo mv Unity\ Hub.app /Applications
            # hdiutil detach "/Volumes/Unity Hub 3.1.1/"      
        - name: Install Unity
          script: | 
            /Applications/Unity\ Hub.app/Contents/MacOS/Unity\ Hub -- --headless install --version 2019.4.34f1 --changeset 6a9faed444f2 
            /Applications/Unity\ Hub.app/Contents/MacOS/Unity\ Hub -- --headless install-modules --version 2019.4.34f1 -m ios android android-sdk-ndk-tools android-open-jdk
        - name: Activate Unity License
          script: | 
            $UNITY_BIN_VERSION -batchmode -quit -logFile -serial ${UNITY_SERIAL?} -username ${UNITY_USERNAME?} -password ${UNITY_PASSWORD?}
        - name: Set up keystore
          script: |
            echo $FCI_KEYSTORE | base64 --decode > $FCI_BUILD_DIR/keystore.keystore            
        - name: Set build number and export Unity
          script: |
            # export NEW_BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks=alpha) + 1))
            export NEW_BUILD_NUMBER=5
            $UNITY_BIN_VERSION -batchmode -quit -logFile -projectPath . -executeMethod BuildScript.$BUILD_SCRIPT -nographics -buildTarget Android      
      artifacts:
        - android/*.aab
        - android/*.apk
      publishing:
        scripts:
          - name: Deactivate Unity License
            script: $UNITY_BIN_VERSION -batchmode -quit -returnlicense -nographics
        # google_play:
        #   # See the following link for information regarding publishing to Google Play - https://docs.codemagic.io/publishing-yaml/distribution/#google-play
        #   credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        #   track: alpha   # Any default or custom track.